### ISSUE TITLE
No SCORM Background.

### ISSUE THREAD

**Issue by kmirojo** [andydennis/angularjs-scorm-wrapper#4]
Hello,

I'm trying to use your library, but i'm really a newbie in these SCORM things, so i would like to ask you, how am I supposed to use it in my existing project? I mean, I really really have no idea of how to use it's mehods or how to make a SCORM package with it, i would be really thankfull.

**Comment by rpigu-i** [comment]
So this is just a wrapper that simplifies making the SCORM calls from your Angular project. You won't be able to generate a package with this. You might want to start here for guidance on SCORM and SCO generation. 

https://scorm.com
